version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - .:/app
      #- /etc/localtime:/etc/localtime:ro 
      #- /etc/timezone:/etc/timezone:ro 
    depends_on:
      - mongodb
    env_file: 
      - ./.env

networks:
  backend: